### ISSUE TITLE
fuo 文件增强

### ISSUE THREAD

**Issue by cosven** [feeluown/FeelUOwn#302]
作者：
创建时间：2020-09-28
最近更新：
最新状态：
- 2020-09-28 - 添加了需求、实现方案等内容
- 2019-12-29 - 描述了 fuo 文件可以有哪些 metadata

## 简介与背景

fuo 文件存在一些已知的问题
1. fuo 文件对 `-` 等特殊字符支持不友好，有的歌曲会解析失败 by 很多群友

大家对 fuo 文件还有一些期望
1. fuo 文件能够支持添加描述，类似专辑介绍 by @cosven

## fuo 文件可以有的元信息

1. 创建时间
2. 更新时间
3. 描述
4. 封面

### 概述
类似 hexo/jekyll 等博客系统那样，我们可以给 fuo 文件加一些 yaml 格式的元信息，我们将这一部分称为 header 部分。fuo 文件记录歌曲、专辑信息的部分，我们称为 body 部分。

在对比方案中，我们主要考虑几个点

1. 可读性，可以人肉阅读并编辑
2. 有较好地容错性：一行/块数据地方出错，不应该影响整个文件的解析
3. 程序解析方便
4. 一个 fuo 文件内容可能不只是 songs，还可能有 albums，artists

### body 方案对比
body 部分，目前大家有多种实现方案。

1. 保持现状，效果类似
    ```bash
    fuo://netease/songs/569213220   # 像我这样的人 - 毛不易 - 平凡的一天 - 03:27
    ```
2. 使用 csv
    ```csv
    fuo://netease/songs/569213220,像我这样的人,毛不易,平凡的一天,03:27
    ```
3. 使用 yaml
    ```yaml
    - uri: fuo://netease/songs/569213220
      title: 像我这样的人
      artists: 毛不易
      album: 平凡的一天
      durtion: 03:27
    ```
4. 使用 json

### body 部分最终方案选择

yaml 和 json 的不好的地方：
1. 对局部错误容忍度不好
2. 可读性一般，重复信息很多

csv 的问题在于
1. 不能容纳异构的内容：比如 song 和 artist

### 小结

fuo 文件可以使用 header + body 的形式。header 部分使用 yaml，甚至自定义一种简单的格式（因为选择 yaml 意味着填一个新的依赖）。body 部分使用原有的格式。

## TODOs

- [ ] 确认 header 格式，并实现相应的 load/dump 逻辑
- [ ] fuo 文件支持解析 header 部分
- [ ] feeluown GUI 实现相应支持

optional

- [ ] 原有格式兼容 `-` 等特殊字符

**Comment by cosven** [comment]
### yaml vs toml

```fuo
---
title = "决定"
created = 2020-08-01T00:00:00-00:00
updated = 2020-11-01T00:00:00-00:00
description = '''
想想是容易的，决定是困难的。
'''
---
fuo://local/songs/1       # 决定 - 刘若英 - 00:00
fuo://local/songs/1       # 决定 - 刘若英 - 00:00
fuo://local/songs/1       # 决定 - 刘若英 - 00:00
fuo://local/songs/1       # 决定 - 刘若英 - 00:00
fuo://local/songs/1       # 决定 - 刘若英 - 00:00
fuo://local/songs/1       # 决定 - 刘若英 - 00:00
```

```fuo
---
title: 决定
created: 2020-08-01T00:00:00-00:00
updated: 2020-11-01T00:00:00-00:00
description:|
  想想是容易的，决定是困难的。
---
fuo://local/songs/1       # 决定 - 刘若英 - 00:00
fuo://local/songs/1       # 决定 - 刘若英 - 00:00
fuo://local/songs/1       # 决定 - 刘若英 - 00:00
fuo://local/songs/1       # 决定 - 刘若英 - 00:00
fuo://local/songs/1       # 决定 - 刘若英 - 00:00
fuo://local/songs/1       # 决定 - 刘若英 - 00:00
```

**Comment by cosven** [comment]
已经完成了 ~
