### ISSUE TITLE
4.0 发版之前的 TODO

### ISSUE THREAD

**Issue by cosven** [feeluown/FeelUOwn#769]
- 降低维护和开发成本
  - [x] 移除对 v1 model 的兼容代码
    - [x] 移除对 v1 model 属性的访问 https://github.com/feeluown/FeelUOwn/pull/765
    - [x] review ProviderNotFound 异常，尽量删掉这个异常 https://github.com/feeluown/FeelUOwn/pull/770
    - [x] review NotSupport 异常，尽量删除这个异常 
- 提升开发效率，避免“弱智bug“
    - [x] 给重要模块加上 type hint https://github.com/feeluown/FeelUOwn/pull/771
      - [x] 让 SongModel 能够继承 BriefSongModel，删掉 model_protocol 模块
    - [x] 在 CI 中重新开启 mypy 检查（或者 pyright 检查？） https://github.com/feeluown/FeelUOwn/pull/771
        暂时不知道为啥，mypy 在本地和 CI 的表现不一样
